[context.production.environment]
SANITY_STUDIO_API_DATASET = "future"

[context.deploy-preview.environment]
SANITY_STUDIO_API_DATASET = "staging"

[[redirects]]
  from = "/program"
  to = "/events?redirectedFrom=/prorgam"
  status = 308
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
