[context.production.environment]
SANITY_STUDIO_API_DATASET = "future"

[context.deploy-preview.environment]
SANITY_STUDIO_API_DATASET = "staging"

[[redirects]]
  from = "/contact"
  to = "/p/contact?redirectedFrom=/contact"
  status = 301

[[redirects]]
  from = "/about"
  to = "/p/about?redirectedFrom=/about"
  status = 301

[[redirects]]
  from = "/program"
  to = "/events?redirectedFrom=/program"
  status = 301
  
[[redirects]]
  from = "/p/pride-art"
  to = "https://www.prideart.no"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
