[context.production.environment]
SANITY_STUDIO_API_DATASET = "future"

[context.deploy-preview.environment]
SANITY_STUDIO_API_DATASET = "staging"

[[redirects]]
  from = "/program"
  to = "https://www.oslopride.no/events?redirectedFrom=/prorgam"
  status = 308

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
