[context.production.environment]
SANITY_STUDIO_API_DATASET = "future"

[context.deploy-preview]
ignore = "git diff --quiet HEAD^ HEAD $BASE_DIR"

[context.deploy-preview.environment]
SANITY_STUDIO_API_DATASET = "staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
